### ISSUE TITLE
Note able to create a bna file in hyperleger composer

### ISSUE THREAD

**Issue by reaachpunnoosejoseph** [nodejs/node-report#128]
composer archive create -a dist/perishable.bna --sourceType dir --sourceName .
internal/modules/cjs/loader.js:730
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '\\?\C:\Users\USER\AppData\Roaming\npm\node_modules\composer-cli\node_modules\node-report\api.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\composer-cli\node_modules\node-report\index.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)

**Comment by sam-github** [comment]
> Please try re-compiling or re-installing the module (for instance, using npm rebuild or npm install).

Hi, please do the above! Your binary dependencies were built with a node version that is incompatible with the node version you are currently running.

Or update to 12.x, where node-report is builtin to node.

cf. https://github.com/nodejs/node/issues/27100
