### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by iPatavatsizz** [nodejs/node-report#145]
I got these errors when rebuild the script before installing @discordjs/opus.

- Node Version: v13.12.0
- Npm: latest.
- Visual Studio: 2017 & 2019 With,
-- C++ Desktop Development Kit
-- C++ Core Features(up.)
-- MSBuild
-- NodeJS Development Toolkit( In VS 2019 )

```
C:\Users\emre\Desktop\discord-opus\node-report-2.2.10>node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@13.12.0 | win32 | ia32
gyp info find Python using Python version 2.7.15 found at "C:\Users\emre\.window
s-build-tools\python27\python.exe"
gyp info find VS using VS2019 (16.5.30002.166) found at:
gyp info find VS "C:\Program Files\Microsoft Visual Studio\2019\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\emre\.windows-build-tools\python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\emre\\AppData\\Roaming\\npm\\node_modules\\nod
e-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\emre\\Desktop\\discord-opus\\node-report-2.2.1
0\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\emre\\AppData\\Roaming\\npm\\node_modules\\nod
e-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\emre\\AppData\\Local\\node-gyp\\Cache\\13.12.0
\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\emre\\AppData\\Local\\node-gyp
\\Cache\\13.12.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\emre\\AppData\\Roaming\\npm\\no
de_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\emre\\\\AppData\\\\Local\\
\\node-gyp\\\\Cache\\\\13.12.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\emre\\Desktop\\discord-opus\
\node-report-2.2.10',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\emre\\Desktop\\discord-opus\\node-report-2.2.1
0\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files\Microsoft Visual Studio\2019\Community\MSBuild\C
urrent\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32'
gyp info spawn args ]
Bu çözümde projeler tek tek derlenir. Paralel bir derlemeyi etkinleştirmek için
lütfen "-m" anahtarını ekleyin.
  node_report.cc
C:\Users\emre\Desktop\discord-opus\node-report-2.2.10\src\node_report.h(4,10):
fatal error C1083: içerme dosyası açılamıyor: 'nan.h': No such file or director
y [C:\Users\emre\Desktop\discord-opus\node-report-2.2.10\build\api.vcxproj]
  module.cc
C:\Users\emre\Desktop\discord-opus\node-report-2.2.10\src\node_report.h(4,10):
fatal error C1083: içerme dosyası açılamıyor: 'nan.h': No such file or director
y [C:\Users\emre\Desktop\discord-opus\node-report-2.2.10\build\api.vcxproj]
  utilities.cc
C:\Users\emre\Desktop\discord-opus\node-report-2.2.10\src\node_report.h(4,10):
fatal error C1083: içerme dosyası açılamıyor: 'nan.h': No such file or director
y [C:\Users\emre\Desktop\discord-opus\node-report-2.2.10\build\api.vcxproj]
  win_delay_load_hook.cc
  Kod Üretiliyor...
^C^CToplu iş sonlandırılsın mı (E/H)? E

C:\Users\emre\Desktop\discord-opus\node-report-2.2.10>node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@13.12.0 | win32 | ia32
gyp info find Python using Python version 2.7.15 found at "C:\Users\emre\.window
s-build-tools\python27\python.exe"
gyp info find VS using VS2019 (16.5.30002.166) found at:
gyp info find VS "C:\Program Files\Microsoft Visual Studio\2019\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\emre\.windows-build-tools\python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\emre\\AppData\\Roaming\\npm\\node_modules\\nod
e-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\emre\\Desktop\\discord-opus\\node-report-2.2.1
0\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\emre\\AppData\\Roaming\\npm\\node_modules\\nod
e-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\emre\\AppData\\Local\\node-gyp\\Cache\\13.12.0
\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\emre\\AppData\\Local\\node-gyp
\\Cache\\13.12.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\emre\\AppData\\Roaming\\npm\\no
de_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\emre\\\\AppData\\\\Local\\
\\node-gyp\\\\Cache\\\\13.12.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\emre\\Desktop\\discord-opus\
\node-report-2.2.10',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\emre\\Desktop\\discord-opus\\node-report-2.2.1
0\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'NaN'
Require stack:
- C:\Users\emre\Desktop\discord-opus\node-report-2.2.10\[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:131:20)
    at Object.runInThisContext (vm.js:297:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at evalScript (internal/process/execution.js:94:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\emre\\Desktop\\discord-opus\\node-report-2.2.10\\[eval]'
  ]
}
**gyp: Call to 'node -e "require('NaN')"' returned exit status 1 while in binding.**
gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\emre\AppData\Roaming\npm\n
ode_modules\node-gyp\lib\configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:275:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\emre\\AppData
\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd C:\Users\emre\Desktop\discord-opus\node-report-2.2.10
gyp ERR! node -v v13.12.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok
```

**MY NOTE:** When i delete require NaN command on binding.gyp#Line:6, Scriot not gives to me any errors but after when i try to rebuild the script, i am getting errors again... Yours can see in this log file.

**Comment by richardlau** [comment]
How did you install node-report? `nan` is listed as a dependency so should have been installed by `npm` (or whatever package manager you used to install `node-report`) automatically. https://github.com/nodejs/node-report/blob/2359180c4935fe88ad66ca64cbcb5ec883b1d2e4/package.json#L14

**Comment by iPatavatsizz** [comment]
> How did you install node-report? `nan` is listed as a dependency so should have been installed by `npm` (or whatever package manager you used to install `node-report`) automatically.
> 
> https://github.com/nodejs/node-report/blob/2359180c4935fe88ad66ca64cbcb5ec883b1d2e4/package.json#L14

Today, i tried again and i got ths error:

```
C:\Users\emre\Desktop\discord-opus\node-report-2.2.10>npm install --global

> node-report@2.2.10 install C:\Users\emre\AppData\Roaming\npm\node_modules\node
-report
> node-gyp rebuild


C:\Users\emre\AppData\Roaming\npm\node_modules\node-report>if not defined npm_co
nfig_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-l
ifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  e
lse (node "C:\Users\Emre\AppData\npm\node-modules\node-gyp.js" rebuild )
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'C:\Users\Emre\AppData\npm\node-modules\node-gyp.js'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976
:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:859:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_ma
in.js:71:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}
npm WARN rollback Rolling back nan@2.14.0 failed (this is probably harmless): C:
\Users\emre\Desktop\discord-opus\node-report-2.2.10\node_modules\nan is not a ch
ild of C:\Users\emre\AppData\Roaming\npm
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-report@2.2.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-report@2.2.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\emre\AppData\Roaming\npm-cache\_logs\2020-04-13T09_07_38_5
71Z-debug.log

C:\Users\emre\Desktop\discord-opus\node-report-2.2.10>
```

**npm WARN rollback Rolling back nan@2.14.0 failed (this is probably harmless): C:
\Users\emre\Desktop\discord-opus\node-report-2.2.10\node_modules\nan is not a ch
ild of C:\Users\emre\AppData\Roaming\npm**

I'll install nan before node-report.

**Comment by richardlau** [comment]
If you extracted/cloned node-report from source you should run npm install in its directory _without_ the `--global` flag.

**Comment by iPatavatsizz** [comment]
> If you extracted/cloned node-report from source you should run npm install in its directory _without_ the `--global` flag.

Thanks, but there is one more thing, I have found out now, in my VS2017, C++ Desktop Development Package aren't exists. I am installing now, Already node-gyp couldn't find 2019's MSBuild.exe because in 2019, msbuild was on Current file. Due to this node-gyp may not install my package(because in 2017, there isn't c++...).

**Comment by richardlau** [comment]
> 
> 
> > If you extracted/cloned node-report from source you should run npm install in its directory _without_ the `--global` flag.
> 
> Thanks, but there is one more thing, I have found out now, in my VS2017, C++ Desktop Development Package aren't exists. I am installing now, Already node-gyp couldn't find 2019's MSBuild.exe because in 2019, msbuild was on Current file. Due to this node-gyp may not install my package(because in 2017, there isn't c++...).

What version of node-gyp/npm are you using? node-gyp should be able to work with VS2019 from version 5 onwards, which should be included in the recent versions of npm.

**Comment by iPatavatsizz** [comment]
> > > If you extracted/cloned node-report from source you should run npm install in its directory _without_ the `--global` flag.
> > 
> > 
> > Thanks, but there is one more thing, I have found out now, in my VS2017, C++ Desktop Development Package aren't exists. I am installing now, Already node-gyp couldn't find 2019's MSBuild.exe because in 2019, msbuild was on Current file. Due to this node-gyp may not install my package(because in 2017, there isn't c++...).
> 
> What version of node-gyp/npm are you using? node-gyp should be able to work with VS2019 from version 5 onwards, which should be included in the recent versions of npm.

I use npm 6.14.4, node-gyp can not find vs 2019's msbuild because MSBuild is on Current/ folder -> _Program Files\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin_ due to this, msbuild.exe can not be found, node-gyp searchs it on 15.0 Folder but it is not on there. Because of this, I switched Visual Studio 2017.

**Comment by richardlau** [comment]
npm 6.14.4 should contain node-gyp 5 which should be able to work with VS2019.

**Comment by iPatavatsizz** [comment]
> npm 6.14.4 should contain node-gyp 5 which should be able to work with VS2019.

You're right, but Although node-gyp aren't getting error, packages aren't be installed, idk why.
Both of two Visual Studios are included C++ Core Packages and I have Python 3.8, Also i am getting errors :"(

**Comment by iPatavatsizz** [comment]
I am trying to install extra packages VS2017 to help node-gyp. I'll try again to install node-report, also i installed nan package and set npm config to use node_gyp path.

**Comment by iPatavatsizz** [comment]
Andd again i got this boring error:

```
C:\Users\emre\Desktop\discord-opus\node-report-2.2.10>npm install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://git
hub.com/request/request/issues/3142

> node-report@2.2.10 install C:\Users\emre\Desktop\discord-opus\node-report-2.2.
10
> node-gyp rebuild


C:\Users\emre\Desktop\discord-opus\node-report-2.2.10>if not defined npm_config_
node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecy
cle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (
node "C:\Users\emre\AppData\Roaming\npm\node-modules\node-gyp\bin\node-gyp.js" r
ebuild )
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'C:\Users\emre\AppData\Roaming\npm\node-modules\node-g
yp\bin\node-gyp.js'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976
:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:859:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_ma
in.js:71:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-report@2.2.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-report@2.2.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\emre\AppData\Roaming\npm-cache\_logs\2020-04-13T12_10_54_6
31Z-debug.log

C:\Users\emre\Desktop\discord-opus\node-report-2.2.10>
```

**Comment by richardlau** [comment]
For it to be looking in `AppData\Roaming\npm\node-modules` suggests a configuration issue with `npm`. This could have happened if you have previously attempted to manually update npm or globally install node-gyp in the past. Maybe try the npm issue tracker or nodejs/help?

**Comment by iPatavatsizz** [comment]
> For it to be looking in `AppData\Roaming\npm\node-modules` suggests a configuration issue with `npm`. This could have happened if you have previously attempted to manually update npm or globally install node-gyp in the past. Maybe try the npm issue tracker or nodejs/help?

Thanks for everything, We can close issue.
